version: "3.8"
services:
  django:
    build: . #represents the build in current directory, dont change
    # container_name: mytrain
    ports:
      - "5000:5000"
    stdin_open: true
    tty: true

  # react-app:
  #   build: ./react-app
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./react-app:/usr/src/app
  #     - /usr/src/app/node_modules
